from adminsortable2.admin import SortableAdminMixin
from django.contrib import admin
from django.utils.safestring import mark_safe
from django.utils.translation import gettext as _
from easy_thumbnails.files import get_thumbnailer

from core.models import SliderItem


@admin.register(SliderItem)
class SliderItemAdmin(SortableAdminMixin, admin.ModelAdmin):
    # todo: fix border style for thumb, that generated by django-filer. Border style reduces the image size and makes
    #  the image blurry. As the way we can use inner shadow instead of border style
    #  see and inspect img tag in admin: /admin/core/slideritem/1/change/
    #  style: form .form-row .filer-dropzone .filerFile img
    list_display = ('image_html', 'title')
    list_display_links = ('image_html', 'title')

    def image_html(self, obj):
        return mark_safe('<img src="{}" />'.format(
            get_thumbnailer(obj.image)['admin_thumb'].url
        )
    )

    image_html.short_description = _('Image')
